# Generated by Django 4.0.5 on 2022-06-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('thumbnail', models.ImageField(upload_to='images/', verbose_name='섬네일')),
                ('content', models.CharField(max_length=120, verbose_name='설명')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('start_propose_date', models.DateTimeField(verbose_name='노출 시작일')),
                ('end_propose_date', models.DateTimeField(verbose_name='노출 종료일')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
