# Generated by Django 4.0.5 on 2022-06-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_event_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='test_active',
            field=models.BooleanField(default=True, verbose_name='test 여부'),
        ),
    ]
