# Generated by Django 4.0.5 on 2022-06-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='카테고리', to='blog.category', verbose_name='카테고리'),
        ),
    ]
